# theme: jekyll-theme-cayman
title: Sustainability Lab
description: IIT Gandhinagar

highlighter: rouge

##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true
