project:
  type: website
  output-dir: docs
  
website:
  title: "Sustainability Lab"
  navbar:
    title: False
    search: true
    left:
      - text: "<img src='/images/logo.png' style='height: 90px !important;'>"
        href: index.qmd  
      - text: People
        menu:
          - text: Current Team
            href: members.qmd
          - text: Alumni
            href: alumni.qmd
          - text: Alumni Experiences
            href: experiences.qmd
          - text: Memories
            href: memories.qmd
      - href: papers/index.qmd
        text: Publications
      - href: openings.qmd
        text: Openings
      - href: lab-handbook.qmd
        text: Lab Handbook  
      - href: news.qmd
        text: News
      - href: media.qmd
        text: Media coverage
      - href: awards.qmd
        text: Awards
  

format:
  html:
    page-layout: full
    toc: true
    grid:
      margin-width: 14%
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
