project:
  type: website
  output-dir: docs
  
website:
  title: "Sustainability Lab"
  navbar:
    title: False
    search: true
    left:
      - text: "<img src='/images/logo.png' style='height: 90px !important;'>"
        href: index.qmd  
      - href: members.qmd
        text: Team
      - href: papers/index.qmd
        text: Publications
      - href: awards.qmd
        text: Awards
      - href: news.qmd
        text: News
      - href: media.qmd
        text: Media coverage
      - href: memories.qmd
        text: Memories
      - href: experiences.qmd
        text: Alumni Experience
      - href: lab-handbook.qmd
        text: Lab Handbook    

format:
  html:
    page-layout: full
    toc: true
    grid:
      margin-width: 14%
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
